Hide deprecated options and few more adjustments

diff --git a/bin/pulsar b/bin/pulsar
--- a/bin/pulsar
+++ b/bin/pulsar
@@ -24,7 +24,6 @@ PULSAR_HOME=`cd $BINDIR/..;pwd`
 DEFAULT_BROKER_CONF=$PULSAR_HOME/conf/broker.conf
 DEFAULT_BOOKKEEPER_CONF=$PULSAR_HOME/conf/bookkeeper.conf
 DEFAULT_ZK_CONF=$PULSAR_HOME/conf/zookeeper.conf
-DEFAULT_GLOBAL_ZK_CONF=$PULSAR_HOME/conf/global_zookeeper.conf
 DEFAULT_CONFIGURATION_STORE_CONF=$PULSAR_HOME/conf/global_zookeeper.conf
 DEFAULT_DISCOVERY_CONF=$PULSAR_HOME/conf/discovery.conf
 DEFAULT_PROXY_CONF=$PULSAR_HOME/conf/proxy.conf
@@ -104,19 +103,19 @@ pulsar_help() {
     cat <<EOF
 Usage: pulsar <command>
 where command is one of:
+
     broker              Run a broker server
     bookie              Run a bookie server
     zookeeper           Run a zookeeper server
-    global-zookeeper    Run a configuration-store server (Deprecated. Use "bin/pulsar configuration-store" instead)
     configuration-store Run a configuration-store server
     discovery           Run a discovery server
     proxy               Run a pulsar proxy
     websocket           Run a web socket proxy server
     functions-worker    Run a functions worker server
     standalone          Run a broker server with local bookies and local zookeeper
-    compact-topic       Run compaction against a topic
 
     initialize-cluster-metadata     One-time metadata initialization
+    compact-topic       Run compaction against a topic
     zookeeper-shell     Open a ZK shell client
 
     help                This help message
@@ -128,8 +127,7 @@ Environment variables:
    PULSAR_BROKER_CONF            Configuration file for broker (default: $DEFAULT_BROKER_CONF)
    PULSAR_BOOKKEEPER_CONF        Configuration file for bookie (default: $DEFAULT_BOOKKEEPER_CONF)
    PULSAR_ZK_CONF                Configuration file for zookeeper (default: $DEFAULT_ZK_CONF)
-   PULSAR_GLOBAL_ZK_CONF         Configuration file for global configuration zookeeper (default: $DEFAULT_GLOBAL_ZK_CONF) (Deprecated. Replace with "PULSAR_CONFIGURATION_STORE_CONF")
-   PULSAR_CONFIGURATION_STORE_CONF         Configuration file for global configuration zookeeper (default: $DEFAULT_CONFIGURATION_STORE_CONF)
+   PULSAR_CONFIGURATION_STORE_CONF         Configuration file for global configuration store (default: $DEFAULT_CONFIGURATION_STORE_CONF)
    PULSAR_DISCOVERY_CONF         Configuration file for discovery service (default: $DEFAULT_DISCOVERY_CONF)
    PULSAR_WEBSOCKET_CONF         Configuration file for websocket proxy (default: $DEFAULT_WEBSOCKET_CONF)
    PULSAR_PROXY_CONF             Configuration file for Pulsar proxy (default: $DEFAULT_PROXY_CONF)
@@ -298,5 +296,8 @@ elif [ $COMMAND == "compact-topic" ]; then
 elif [ $COMMAND == "help" ]; then
     pulsar_help;
 else
-    exec $JAVA $OPTS $COMMAND $@
+    echo ""
+    echo "-- Invalid command '$COMMAND' -- Use '$0 help' to get a list of valid commands"
+    echo ""
+    exit 1
 fi
