Fix a minor bug

diff --git a/bin/pulsar-daemon b/bin/pulsar-daemon
--- a/bin/pulsar-daemon
+++ b/bin/pulsar-daemon
@@ -53,13 +53,15 @@ PULSAR_PID_DIR=${PULSAR_PID_DIR:-$PULSAR_HOME/bin}
 if [ $# = 0 ]; then
     usage
     exit 1
-elif [ $# = 1 -a $1 == "--help" -o $1 == "-h" ]; then
-    usage
-    exit 1
-else
-    echo "Error: no enough arguments provided."
-    usage
-    exit 1
+elif [ $# = 1 ]; then
+    if [ $1 == "--help" -o $1 == "-h" ]; then
+        usage
+        exit 1
+    else
+        echo "Error: no enough arguments provided."
+        usage
+        exit 1
+    fi
 fi
 
 startStop=$1
